# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/janux/src/experimental-software/csort

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/janux/src/experimental-software/csort

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/janux/src/experimental-software/csort/CMakeFiles /home/janux/src/experimental-software/csort//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/janux/src/experimental-software/csort/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named csort

# Build rule for target.
csort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 csort
.PHONY : csort

# fast build rule for target.
csort/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csort.dir/build.make CMakeFiles/csort.dir/build
.PHONY : csort/fast

src/Sorting.o: src/Sorting.c.o
.PHONY : src/Sorting.o

# target to build an object file
src/Sorting.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csort.dir/build.make CMakeFiles/csort.dir/src/Sorting.c.o
.PHONY : src/Sorting.c.o

src/Sorting.i: src/Sorting.c.i
.PHONY : src/Sorting.i

# target to preprocess a source file
src/Sorting.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csort.dir/build.make CMakeFiles/csort.dir/src/Sorting.c.i
.PHONY : src/Sorting.c.i

src/Sorting.s: src/Sorting.c.s
.PHONY : src/Sorting.s

# target to generate assembly for a file
src/Sorting.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csort.dir/build.make CMakeFiles/csort.dir/src/Sorting.c.s
.PHONY : src/Sorting.c.s

src/Utils.o: src/Utils.c.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csort.dir/build.make CMakeFiles/csort.dir/src/Utils.c.o
.PHONY : src/Utils.c.o

src/Utils.i: src/Utils.c.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csort.dir/build.make CMakeFiles/csort.dir/src/Utils.c.i
.PHONY : src/Utils.c.i

src/Utils.s: src/Utils.c.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csort.dir/build.make CMakeFiles/csort.dir/src/Utils.c.s
.PHONY : src/Utils.c.s

src/csort.o: src/csort.c.o
.PHONY : src/csort.o

# target to build an object file
src/csort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csort.dir/build.make CMakeFiles/csort.dir/src/csort.c.o
.PHONY : src/csort.c.o

src/csort.i: src/csort.c.i
.PHONY : src/csort.i

# target to preprocess a source file
src/csort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csort.dir/build.make CMakeFiles/csort.dir/src/csort.c.i
.PHONY : src/csort.c.i

src/csort.s: src/csort.c.s
.PHONY : src/csort.s

# target to generate assembly for a file
src/csort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/csort.dir/build.make CMakeFiles/csort.dir/src/csort.c.s
.PHONY : src/csort.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... csort"
	@echo "... src/Sorting.o"
	@echo "... src/Sorting.i"
	@echo "... src/Sorting.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/csort.o"
	@echo "... src/csort.i"
	@echo "... src/csort.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

